name: Build Project

on:
  push:
    branches:
      - Development
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install PlatformIO CLI
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Install PlatformIO Core
      run: platformio update

    - name: Build project
      working-directory: ./Shadow%20Duck%20Firmware
      run: platformio run --environment pico
